function credit_text(){
	
	var text_array=[
		"CREADO POR\n\n"+
		"SOFÍA ALEJANDRA SALAS\n"+
		"ALEXANDRA BERNAL\n"+
		"NICOLLE FABIANA CADAVID\n"+
		"DAVID SANTIAGO CÁRDENAS\n"+
		"JOSÉ GABRIEL REYES",
		"DESARROLLADO POR\n\n"+
		"ALEXANDRA BERNAL\n"+
		"DAVID SANTIAGO CÁRDENAS\n"+
		"JOSÉ GABRIEL REYES",
		"DISEÑADO GRÁFICAMENTE POR\n\n"+
		"SOFIA ALEJANDRA SALAS\n"+
		"NICOLLE FABIANA CADAVID\n"+
		"DAVID SANTIAGO CÁRDENAS",
		"HISTORIA HECHA POR\n\n"+
		"SOFIA ALEJANDRA SALAS\n"+
		"NICOLLE FABIANA CADAVID\n"+
		"DAVID SANTIAGO CÁRDENAS",
		"MÚSICA HECHA POR\n\n"+
		"DAVID SANTIAGO CÁRDENAS\n"+
		"SOFÍA ALEJANDRA SALAS"
	];
	
	return text_array;
}